### ISSUE TITLE
IPython.core.profiledir.ProfileDirError: Profile directory not found in paths: profile_default

### ISSUE THREAD

**Issue by weems** [ivanov/bipython#16]
Traceback (most recent call last):
  File "/usr/local/bin/bipython", line 9, in <module>
    load_entry_point('bipython==0.1.2', 'console_scripts', 'bipython')()
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bipython/**init**.py", line 1769, in main
    myrepl = URWIDRepl(event_loop, palette, interpreter, config)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bipython/**init**.py", line 651, in **init**
    self.ipython = self.connect_ipython_kernel()
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bipython/**init**.py", line 706, in connect_ipython_kernel
    fullpath = find_connection_file(s.lstrip().rstrip())
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/kernel/connect.py", line 212, in find_connection_file
    profile_dir = ProfileDir.find_profile_dir_by_name(get_ipython_dir(), 'default')
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/profiledir.py", line 264, in find_profile_dir_by_name
    raise ProfileDirError('Profile directory not found in paths: %s' % dirname)
IPython.core.profiledir.ProfileDirError: Profile directory not found in paths: profile_default

**Comment by msoucy** [comment]
It makes it easier to read if you wrap the text in "```", so it doesn't format anything improperly.

I fixed that by running `ipython` once first.
