### ISSUE TITLE
Can't start bipython

### ISSUE THREAD

**Issue by MattBlack85** [ivanov/bipython#17]
After installing all the components, when typing `bipython` into the terminal I get:

```
Traceback (most recent call last):
  File "/bin/bipython", line 9, in <module>
    load_entry_point('bipython==0.1.2', 'console_scripts', 'bipython')()
  File "/usr/lib/python2.7/site-packages/bipython/__init__.py", line 1769, in main
    myrepl = URWIDRepl(event_loop, palette, interpreter, config)
  File "/usr/lib/python2.7/site-packages/bipython/__init__.py", line 651, in __init__
    self.ipython = self.connect_ipython_kernel()
  File "/usr/lib/python2.7/site-packages/bipython/__init__.py", line 708, in connect_ipython_kernel
    self.echod(":IPython " + s + " failed", "Info")
TypeError: echod() takes exactly 2 arguments (3 given)

```

any idea?

**Comment by MarkusLohmayer** [comment]
I am having the same error having installed bipython through pip.
Actually I was seeing a different error yet before having installed a few more packages that also prevented me from starting the new ipython notebook so it may be a dependency issue ...
Now I am on this error too and still curious to try bipython.
greetings!

**Comment by fxlv** [comment]
Any luck solving this?
Just installed bipython from pip on OSX (python2.7) and see same error.
