### ISSUE TITLE
Install troubles ('ZMQSocketChannel' object has no attribute 'execute')

### ISSUE THREAD

**Issue by stsievert** [ivanov/bipython#20]
After running `bipython` after running `ipython console` or `ipython kernel` I get 

``` shell
> bipython
fatal: Not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/Users/scott/anaconda/bin/bipython", line 9, in <module>
    load_entry_point('bipython==0.1.3.-f261b78-', 'console_scripts', 'bipython')()
  File "/Users/scott/anaconda/lib/python2.7/site-packages/bipython-0.1.3._f261b78_-py2.7.egg/bipython/__init__.py", line 1860, in main
    myrepl = URWIDRepl(event_loop, palette, interpreter, config)
  File "/Users/scott/anaconda/lib/python2.7/site-packages/bipython-0.1.3._f261b78_-py2.7.egg/bipython/__init__.py", line 728, in __init__
    self.ipython = self.connect_ipython_kernel()
  File "/Users/scott/anaconda/lib/python2.7/site-packages/bipython-0.1.3._f261b78_-py2.7.egg/bipython/__init__.py", line 817, in connect_ipython_kernel
    self.send_ipython = kc.shell_channel.execute
AttributeError: 'ZMQSocketChannel' object has no attribute 'execute'
```

I'd really like to use bipython.

**Comment by CallumHoward** [comment]
I also encountered this same error, I'm unable to use bipython.

**Comment by abcdw** [comment]
up! I have the same error.

**Comment by bhargavrpatel** [comment]
I do not think that @ivanov is supporting this project anymore.

**Comment by stsievert** [comment]
Agreed. When I was looking for replacements, I found [ptpython](https://github.com/jonathanslenders/ptpython). It's another interpreter with many of the same features -- auto completion, syntax highlighting, IPython integration and it can docstrings as you type.

**Comment by abcdw** [comment]
Thanks a lot. It's look good.

сб, 25 июля 2015, 20:25, Scott S. notifications@github.com:
