### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by programes** [ivanov/bipython#25]
Traceback (most recent call last):
  File "/home/fjc/.pyenv/versions/3.5.0/bin/bipython", line 9, in <module>
    load_entry_point('bipython==0.1.2', 'console_scripts', 'bipython')()
  File "/home/fjc/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pkg_resources/**init**.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/fjc/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pkg_resources/**init**.py", line 2697, in load_entry_point
    return ep.load()
  File "/home/fjc/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pkg_resources/**init**.py", line 2370, in load
    return self.resolve()
  File "/home/fjc/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pkg_resources/**init**.py", line 2376, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/home/fjc/.pyenv/versions/3.5.0/lib/python3.5/site-packages/bipython/**init**.py", line 161
    print sys.exc_info()
            ^
SyntaxError: invalid syntax

**Comment by wookayin** [comment]
Why no python3?

**Comment by wookayin** [comment]
@ivanov Do you still maintain this?
