### ISSUE TITLE
IPython version dependency

### ISSUE THREAD

**Issue by rkern** [ivanov/bipython#4]
`setup.py` claims `>= 0.12`, but it does not appear to work with 1.2.1 or 1.1.0:

```
[~]$ ipython
Python 2.7.3 | 64-bit | (default, Aug  8 2013, 05:37:06)
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

[~]
|1>
Do you really want to exit ([y]/n)?
[~]$ bipython
Traceback (most recent call last):
  File "/Users/rkern/Library/Enthought/Canopy_64bit/User/bin/bipython", line 10, in <module>
    sys.exit(main())
  File "/Users/rkern/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bipython/__init__.py", line 1769, in main
    myrepl = URWIDRepl(event_loop, palette, interpreter, config)
  File "/Users/rkern/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bipython/__init__.py", line 651, in __init__
    self.ipython = self.connect_ipython_kernel()
  File "/Users/rkern/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bipython/__init__.py", line 712, in connect_ipython_kernel
    km.load_connection_file()
  File "/Users/rkern/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/kernel/connect.py", line 495, in load_connection_file
    setattr(self, name, cfg[name])
KeyError: 'control_port'
```

**Comment by ivanov** [comment]
oh man, I suck at releasing.... Thanks for the report, I'll get on it after I get some sleep...

we really should stop moving those APIs around in IPython though - a lot of this code I just grabbed from vim-ipython - and boy is it a mess after managing all version bumps from 0.11 on forward...

I was a little too optimistic with 0.12 without testing anything...

**Comment by scopatz** [comment]
> we really should stop moving those APIs around in IPython though - a lot of this code I just grabbed from vim-ipython - and boy is it a mess after managing all version bumps from 0.11 on forward...

Yes.  Yes you should :)

**Comment by lodagro** [comment]
I get a similar exception for ipython 2.0.0 (running the notebook), python 2.7.5

``` python
Traceback (most recent call last):
  File "<...>/bin/bipython", line 9, in <module>
    load_entry_point('bipython==0.1.2', 'console_scripts', 'bipython')()
  File "<...>/lib/python2.7/site-packages/bipython/__init__.py", line 1769, in main
    myrepl = URWIDRepl(event_loop, palette, interpreter, config)
  File "<...>/lib/python2.7/site-packages/bipython/__init__.py", line 651, in __init__
    self.ipython = self.connect_ipython_kernel()
  File "<...>/lib/python2.7/site-packages/bipython/__init__.py", line 712, in connect_ipython_kernel
    km.load_connection_file()
  File "<...>/lib/python2.7/site-packages/IPython/kernel/connect.py", line 498, in load_connection_file
    self.ip = cfg['ip']
KeyError: 'ip'
```
