### ISSUE TITLE
URWIDRepl.echod: two arguments or three?

### ISSUE THREAD

**Issue by mattjj** [ivanov/bipython#6]
On the current master, URWIDRepl.echod [is defined to take one non-self argument](https://github.com/ivanov/bipython/blob/01668af0255ef3166a9ab8af6fb79be0f847d2d6/bipython/__init__.py#L884), but in some places, like [connect_ipython_kernel](https://github.com/ivanov/bipython/blob/01668af0255ef3166a9ab8af6fb79be0f847d2d6/bipython/__init__.py#L708), it's called with two non-self arguments. That gave me this error (when trying to print another error):

```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin/bipython", line 9, in <module>
    load_entry_point('bipython==0.1.2', 'console_scripts', 'bipython')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bipython-0.1.2-py2.7.egg/bipython/__init__.py", line 1769, in main
    myrepl = URWIDRepl(event_loop, palette, interpreter, config)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bipython-0.1.2-py2.7.egg/bipython/__init__.py", line 651, in __init__
    self.ipython = self.connect_ipython_kernel()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bipython-0.1.2-py2.7.egg/bipython/__init__.py", line 708, in connect_ipython_kernel
    self.echod(":IPython " + s + " failed", "Info")
TypeError: echod() takes exactly 2 arguments (3 given)
```

What's the intended signature?

**Comment by mattjj** [comment]
Btw, the error it was trying to print ended with

```
AttributeError: 'URWIDRepl' object has no attribute 'kc'
```

That was really a HumanDocReadingError because I hadn't run `ipython console` first, as per the README.

**Comment by chrisjordansquire** [comment]
This is the same error I ran into. I was using Ipython 2.

**Comment by ivanov** [comment]
@mattjj in your defense, that readme is kinda long though, and there are TWO of 'em. **SPOILER ALERT!** They all die at the end... ;)

**Comment by ivanov** [comment]
Thank you both for reporting, I think I've addressed this in master with a more informative error message on exit. It was already there, but only worked if you were running the latest IPython.
